contact:
  github: atanderson
  email: atanderson89@gmail.com

markdown: redcarpet
highlighter: pygments
permalink: /:title/

sass:
  style: :expanded

gems:
  - jekyll-sitemap

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME